version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cozystay-backend
    ports:
      - "8084:8084"
    networks:
      - cozystay-net
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: cozystay-frontend
    ports:
      - "3000:80"
    networks:
      - cozystay-net
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: cozystay-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cozystay
    networks:
      - cozystay-net

networks:
  cozystay-net:
